spring:
  datasource:
    url: jdbc:mysql://awseb-e-4wdwfpymf2-stack-awsebrdsdatabase-g3jwqpeupbrh.ceajyapu69b8.ap-northeast-2.rds.amazonaws.com:3306/blogdb
    username: park
    password: kds43965
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update  # ???? DB ???? ?????? ?? (??)
  defer-datasource-initialization: true