spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 190394142348-o5fkastk4c12vg2mn5ugtrkcov82djfc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile