spring:
  profiles.include:
    - db
    - oauth2
    - jwt


#  예를 들어 application-s3.yml에 작성해놓은 accessKey를 가져오고 싶은경우 아래와 같이 코드를 작성하면 설정값을 가져올 수 있다.
#
#  @Value("${cloud.aws.credentials.accessKey}")
#  private String accessKey;